# Generated by Django 4.1.7 on 2023-03-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='cotent',
            new_name='content',
        ),
    ]
