# Generated by Django 4.1.7 on 2023-03-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0007_answer_voter_question_voter_alter_answer_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.CharField(default="free", max_length=20),
            preserve_default=False,
        ),
    ]
